# Generated by Django 4.1.3 on 2023-01-29 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='rating_article',
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='number_views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_art/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time_create',
            field=models.TimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time_update',
            field=models.TimeField(auto_now=True, verbose_name='Время последнего изменения'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='topic',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', to='articles.articles', verbose_name='Статьи'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name_tag',
            field=models.CharField(max_length=20, verbose_name='Название тега'),
        ),
    ]
