# Generated by Django 4.1.3 on 2023-01-29 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos_user/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.TextField(blank=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating_author',
            field=models.IntegerField(default=0, verbose_name='Рейтинг автора'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('u', 'обычный пользователь'), ('p', 'премиум пользователь')], default='u', max_length=1, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Имя пользователя'),
        ),
    ]
